"""
India Coffee Recommender Chatbot - first-cut prototype
--------------------------------------------------------
No paid API needed. Uses:
  - streamlit  (free, open source) for the chat UI
  - pandas     (free) to filter the product dataset
  - difflib    (built into Python) for typo-tolerant matching,
               e.g. "Chikmong Lurong" -> "Chikmagalur"

Run locally with:  streamlit run app.py
"""

import csv
import difflib
import os
import random
import re
from datetime import datetime

import pandas as pd
import streamlit as st

# ---------- CONFIG ----------
GOOGLE_FORM_URL = "https://forms.gle/REPLACE_WITH_YOUR_FORM_LINK"  # <-- put your feedback form link here

CLOSING_MESSAGES = [
    "I really hope this cup makes your day better! ☕😊",
    "I hope you found exactly what you were craving! 🌟",
    "Wishing you a wonderful cup of coffee — I'm so glad I could help! 💛",
    "I hope this was worth the wait — enjoy every sip! ☕",
]
LOG_FILE = "interaction_log.csv"  # local usage log for your capstone analysis
RATING_LOG_FILE = "ratings_log.csv"  # per-recommendation star ratings
IMAGE_DIR = "images"  # local placeholder icons, generated by make_icons.py

BREW_FORMAT_ICON = {
    "Traditional Filter": "traditional_filter.png",
    "Ground Powder": "ground_powder.png",
    "Whole Bean": "whole_bean.png",
    "Drip Bag": "drip_bag.png",
    "Instant Sachet": "instant_sachet.png",
    "Cold Brew Concentrate": "cold_brew_concentrate.png",
    "Capsule/Pod": "capsule_pod.png",
    "Milk Premix (3-in-1, With Sugar)": "milk_premix.png",
    "Milk Premix (2-in-1, No Sugar)": "milk_premix_no_sugar.png",
    "Ready-to-Drink": "ready_to_drink.png",
    "Liquid Decoction": "liquid_decoction.png",
}

GREETING_REPLIES = [
    "Hi there! Tell me a region, a flavor, or how strong you like your coffee, and I'll suggest a few options.",
    "Hey! Good day for a coffee, isn't it? ☕ Tell me what you're in the mood for.",
    "Hello! Feeling like something strong, or a milder cup today? Let me know your taste.",
]

STATE_FLAIR = {
    "Karnataka": "Ooh, Karnataka! 🌄 That's the heartland of Indian coffee — cool hill air and shade-grown estates.",
    "Kerala": "Kerala's misty Western Ghats grow some lovely, mellow coffee. 🌿",
    "Tamil Nadu": "Tamil Nadu's Nilgiris — the Blue Mountains — grow beautifully bright, fruity coffee. 🏞️",
    "Andhra Pradesh": "Araku Valley in Andhra Pradesh has a great story — organic, tribal-farmed coffee. 🌱",
    "Meghalaya": "Meghalaya's coffee scene is still young but full of character. ☁️",
    "Assam": "Assam's better known for tea, but its coffee estates are a newer, exciting story. 🍃",
}

QUICK_START_PROMPTS = [
    "Strong filter coffee from Chikmagalur",
    "Mild coffee with oat milk",
    "What brands are available in Araku Valley?",
    "Coffee under ₹250",
    "I want a drip bag, not sachet",
]

STRENGTH_KEYWORDS = {
    "strong": ["strong", "bold", "intense", "dark"],
    "medium": ["medium", "regular", "balanced"],
    "mild": ["mild", "light", "soft", "gentle"],
}
MILK_KEYWORDS = {
    "Almond": ["almond"],
    "Oat": ["oat"],
    "Soya": ["soya", "soy"],
    "Coconut": ["coconut"],
    "Black": ["black", "no milk", "without milk", "no-milk"],
    "Dairy": ["dairy", "regular milk", "full cream", "toned milk", "plain milk"],
}
# phrases that mean "tell me what milk options exist" rather than a specific choice
MILK_LOOKUP_PHRASES = ["what milk", "which milk", "types of milk",
                        "milk options", "different milk", "kind of milk",
                        "don't know what type", "dont know what type"]

BREW_FORMAT_KEYWORDS = {
    "Milk Premix (2-in-1, No Sugar)": ["2 in 1", "2-in-1", "no sugar", "without sugar",
                                          "sugar free", "sugar-free", "unsweetened"],
    "Milk Premix (3-in-1, With Sugar)": ["premix", "pre mix", "3 in 1", "3-in-1",
                                            "all in one", "all-in-1", "milk powder",
                                            "milk and coffee powder", "already has milk",
                                            "no need to add milk", "with sugar"],
    "Capsule/Pod": ["capsule", "capsules", "pod", "pods", "nespresso",
                     "espresso machine", "espresso pod", "coffee pod",
                     "pod machine", "machine coffee"],
    "Drip Bag": ["drip bag", "dip bag", "coffee bag", "dip the bag",
                  "hanging bag", "tea bag style", "dip and brew"],
    "Traditional Filter": ["traditional filter", "south indian filter",
                             "metal filter", "tumbler filter"],
    "Ground Powder": ["ground powder", "ground coffee", "powder"],
    "Liquid Decoction": ["decoction", "liquid decoction", "coffee decoction",
                           "ready to pour", "add hot milk", "pouch decoction"],
    "Whole Bean": ["whole bean", "whole beans", "beans"],
    "Cold Brew Concentrate": ["cold brew", "concentrate"],
    "Ready-to-Drink": ["ready to drink", "ready-to-drink", "rtd", "canned coffee",
                         "cold coffee can", "no preparation needed"],
    "Instant Sachet": ["sachet", "instant", "single serve packet", "stick pack",
                        "rupee pack", "small packet"],
}
BREW_FORMAT_LOOKUP_PHRASES = ["what format", "which format", "types of coffee",
                               "different types of coffee", "how is it brewed",
                               "how do i make it", "how to prepare", "brew formats"]

FLAVOR_KEYWORDS = ["chocolate", "vanilla", "fruity", "floral", "nutty",
                    "caramel", "citrus", "honey", "earthy", "woody",
                    "spicy", "winey", "bold", "less caffeine", "half caff",
                    "half-caff", "low caffeine", "decaf"]
FLAVOR_TRIGGER_WORDS = ["flavor", "flavour", "taste", "tasting", "tastes like"]

TYPE_KEYWORDS = ["filter coffee", "espresso", "cold brew", "instant"]

PACKAGING_KEYWORDS = {
    "Glass Jar": ["glass jar", "jar", "glass bottle", "jar packaging"],
    "Pouch/Packet": ["pouch", "packet", "plastic pack", "foil pack", "bag packaging"],
    "Sachet Box": ["sachet box", "box of sachets"],
    "Capsule Pack": ["capsule pack", "pod pack"],
}
PACKAGING_LOOKUP_PHRASES = ["what packaging", "which packaging", "packet or jar",
                              "jar or packet", "types of packaging", "packaging options",
                              "cover package", "cover packaging"]

# well-known coffee brands/products that are NOT Indian-grown/sourced -
# this bot is scoped to Indian coffee only, so these get an explicit
# "out of scope" reply rather than a generic no-match
FOREIGN_BRAND_KEYWORDS = ["starbucks", "lavazza", "davidoff", "illy", "folgers",
                            "maxwell house", "jacobs", "costa coffee", "peet's",
                            "peets", "blue bottle", "dunkin", "wild vanilla",
                            "colombian brew wild vanilla"]

# words/phrases that mean "this message is coffee-related" even if no
# region/strength/milk/flavor entity was found (e.g. "show me some coffee")
GENERIC_COFFEE_KEYWORDS = ["coffee", "kaapi", "brew", "roast", "bean",
                            "decoction", "cafe", "café", "caffeine", "milk", "sachet"]

BUDGET_VAGUE_KEYWORDS = ["cheap", "affordable", "budget friendly", "budget-friendly",
                          "low cost", "inexpensive", "pocket friendly"]

GREETING_KEYWORDS = ["hi", "hello", "hey", "good morning",
                      "good afternoon", "good evening", "namaste"]

OFF_TOPIC_MESSAGE = (
    "I'm a chatbot built specifically for Indian coffee recommendations — "
    "that's outside what I can help with. But I'd love to help you find "
    "your perfect coffee! Try telling me a region (like Chikmagalur or "
    "Araku Valley), or a preference like strong/mild or dairy/almond milk."
)

# ---------- DATA ----------
@st.cache_data
def load_data():
    products = pd.read_csv("coffee_products_india.csv")
    regions = pd.read_csv("coffee_regions_india.csv")
    return products, regions

products, regions = load_data()

REGION_VOCAB = sorted(set(products["Region"]) | set(regions["Region"]))
REGIONS_WITH_PRODUCTS = sorted(set(products["Region"]))  # for the dropdown - avoid selectable regions with zero real products
STATE_VOCAB = sorted(set(products["State"]) | set(regions["State"]))
BRAND_VOCAB = sorted(products["Brand"].unique())


def _strip_generic_words(name):
    """Remove generic coffee-vocabulary words (e.g. 'Coffee') from a brand
    name for matching purposes only - the original name is still what gets
    stored as the matched entity. Needed because brands like 'Araku Coffee'
    or 'Tata Coffee' are commonly searched by their distinctive word alone."""
    kept = [w for w in name.split() if w.lower() not in GENERIC_COFFEE_KEYWORDS]
    return " ".join(kept) if kept else name


BRAND_MATCH_ALIASES = {_strip_generic_words(b): b for b in BRAND_VOCAB
                        if _strip_generic_words(b) != b}
PRODUCT_VOCAB = sorted(products["Product_Name"].unique())
PRODUCT_NAME_STOPWORDS = {"estate", "estates", "coffee", "roast", "roasted",
                            "blend", "original", "the", "of", "with", "a", "for",
                            "capsule", "capsules", "pod", "pods", "sachet", "sachets",
                            "bag", "bags", "powder"}


def match_product_name(text, cutoff=0.5, min_precision=0.5):
    """Word-overlap matcher for specific product/estate names (e.g. 'Krishnagiri
    Estate'). Unlike the region/brand matcher, this uses set overlap rather than
    character windows, since product names are often longer than what someone
    actually types (e.g. 'krishnagiri dark roast' vs 'Krishnagiri Estate (Dark Roast)').
    Requires both recall (how much of the product name is covered) and precision
    (how much of the query is explained by the product) to be high, so a broad
    browsing query like 'strong filter coffee from Chikmagalur' doesn't get
    wrongly narrowed to one specific product just because those words happen to
    also appear in that product's name."""
    text_words = set(re.findall(r"[a-z0-9]+", text.lower().replace(".", "")))
    if not text_words:
        return None, 0.0
    best, best_score = None, 0.0
    for name in PRODUCT_VOCAB:
        name_words = set(re.findall(r"[a-z0-9]+", name.lower().replace(".", ""))) - PRODUCT_NAME_STOPWORDS
        if not name_words:
            continue
        overlap = text_words & name_words
        if not overlap:
            continue
        recall = len(overlap) / len(name_words)
        precision = len(overlap) / len(text_words)
        if precision < min_precision or len(overlap) < 2:
            continue
        if recall > best_score:
            best_score, best = recall, name
    return (best, best_score) if best_score >= cutoff else (None, 0.0)


# ---------- FUZZY ENTITY EXTRACTION ----------
def _best_fuzzy_match(text, vocab, cutoff=0.7, exclude_words=None):
    """Find the vocab entry that best fuzzy-matches something in `text`.
    Tries word windows of length 1-3, plus a no-space concatenation,
    so misheard/typo'd multi-word names (e.g. 'Chikmong Lurong') still
    match single-word region names (e.g. 'Chikmagalur').
    exclude_words: window text (e.g. 'coffee') that should never be treated
    as a match candidate, even if it scores high by coincidence - needed
    because generic words like 'coffee' or 'bean' can score deceptively
    high against brand names like 'Coffeeza' or 'Beanstalk'."""
    text_l = text.lower()
    words = text_l.split()
    exclude = set(exclude_words or [])
    best, best_score = None, 0.0

    for candidate in vocab:
        cand_l = candidate.lower()
        cand_words = cand_l.split()
        n = len(cand_words)
        for i in range(len(words) - n + 1):
            window = " ".join(words[i:i + n])
            if window in exclude:
                continue
            score = difflib.SequenceMatcher(None, window, cand_l).ratio()
            if score > best_score:
                best_score, best = score, candidate
        # also try a 2-word window concatenated with no space, in case
        # a one-word name got typed/misheard as two words
        for i in range(len(words) - 1):
            if words[i] in exclude or words[i + 1] in exclude:
                continue
            concat = words[i] + words[i + 1]
            score = difflib.SequenceMatcher(None, concat, cand_l.replace(" ", "")).ratio()
            if score > best_score:
                best_score, best = score, candidate

    return (best, best_score) if best_score >= cutoff else (None, 0.0)


def extract_entities(text):
    text_l = text.lower()
    entities = {}

    foreign_match = next((b for b in FOREIGN_BRAND_KEYWORDS if b in text_l), None)
    if foreign_match:
        entities["foreign_brand"] = foreign_match

    region, score = _best_fuzzy_match(text, REGION_VOCAB)
    if region:
        entities["region"] = region
    else:
        state, score = _best_fuzzy_match(text, STATE_VOCAB)
        if state:
            entities["state"] = state

    brand, score = _best_fuzzy_match(text, BRAND_VOCAB, cutoff=0.9, exclude_words=GENERIC_COFFEE_KEYWORDS)
    if not brand and BRAND_MATCH_ALIASES:
        alias, score = _best_fuzzy_match(text, list(BRAND_MATCH_ALIASES.keys()),
                                           cutoff=0.9, exclude_words=GENERIC_COFFEE_KEYWORDS)
        if alias:
            brand = BRAND_MATCH_ALIASES[alias]
    if brand:
        entities["brand"] = brand

    product_name, score = match_product_name(text)
    if product_name:
        entities["product_name"] = product_name

    for level, keywords in STRENGTH_KEYWORDS.items():
        if any(k in text_l for k in keywords):
            entities["strength"] = level.capitalize()
            break

    if any(p in text_l for p in MILK_LOOKUP_PHRASES):
        entities["milk_lookup"] = True
    else:
        for milk_type, keywords in MILK_KEYWORDS.items():
            if any(k in text_l for k in keywords):
                entities["milk"] = milk_type
                break

    for flavor in FLAVOR_KEYWORDS:
        if flavor in text_l:
            entities["flavor"] = flavor
            break
    if "flavor" not in entities and "milk" not in text_l and any(w in text_l for w in FLAVOR_TRIGGER_WORDS):
        entities["unknown_flavor"] = True

    for t in TYPE_KEYWORDS:
        if t in text_l:
            entities["type"] = t.title()
            break

    if any(p in text_l for p in PACKAGING_LOOKUP_PHRASES):
        entities["packaging_lookup"] = True
    else:
        for pack_type, keywords in PACKAGING_KEYWORDS.items():
            if any(k in text_l for k in keywords):
                entities["packaging"] = pack_type
                break

    if any(p in text_l for p in BREW_FORMAT_LOOKUP_PHRASES):
        entities["brew_format_lookup"] = True
    else:
        for fmt, keywords in BREW_FORMAT_KEYWORDS.items():
            if any(k in text_l for k in keywords):
                entities["brew_format"] = fmt
                break

    budget_match = re.search(r"(?:under|below|less than|within)\s*(?:rs\.?|₹)?\s*(\d+)", text_l)
    range_match = re.search(r"(?:between|priced)?\s*(?:rs\.?|₹)?\s*(\d+)\s*(?:to|-|and)\s*(?:rs\.?|₹)?\s*(\d+)", text_l)
    above_match = re.search(r"above\s*(?:rs\.?|₹)?\s*(\d+)", text_l)
    bare_price_match = re.search(r"(?:₹\s*(\d+)|(\d+)\s*(?:rs\.?|rupees?))\b", text_l)
    if range_match:
        entities["budget_min"] = int(range_match.group(1))
        entities["budget"] = int(range_match.group(2))
    elif above_match:
        entities["budget_min"] = int(above_match.group(1))
    elif budget_match:
        entities["budget"] = int(budget_match.group(1))
    elif bare_price_match:
        # informal phrasing like "2rs product" or "₹2 coffee" with no under/below/above -
        # treat the mentioned number as the price ceiling, the most sensible interpretation
        entities["budget"] = int(bare_price_match.group(1) or bare_price_match.group(2))
    elif any(k in text_l for k in BUDGET_VAGUE_KEYWORDS):
        entities["budget"] = 250  # rough "budget option" cutoff, tune as you collect real prices

    pack_size_match = re.search(r"(\d+)\s*(?:gram|grams|gm|g)\b", text_l)
    if pack_size_match:
        entities["requested_grams"] = int(pack_size_match.group(1))

    entities["is_lookup"] = any(w in text_l for w in
                                 ["what brand", "which brand", "available in", "brands in", "options in"])
    return entities


def message_scope(text, entities):
    """Returns 'greeting', 'coffee', or 'off_topic'."""
    text_l = text.lower().strip()

    if any(g in text_l for g in GREETING_KEYWORDS) and len(text_l.split()) <= 4:
        return "greeting"

    # any recognized coffee entity (region/state/strength/milk/flavor/type/brew_format)
    # is enough to count the message as coffee-related
    if any(k in entities for k in ("product_name", "brand", "foreign_brand", "region", "state", "strength", "milk", "flavor",
                                    "type", "brew_format", "packaging", "milk_lookup",
                                    "brew_format_lookup", "packaging_lookup", "budget")):
        return "coffee"

    if any(k in text_l for k in GENERIC_COFFEE_KEYWORDS):
        return "coffee"

    return "off_topic"


# ---------- RECOMMENDATION LOGIC ----------
def filter_products(entities):
    df = products.copy()
    if "product_name" in entities and not entities.get("is_lookup"):
        return df[df["Product_Name"] == entities["product_name"]]
    if "brand" in entities and not entities.get("is_lookup"):
        df = df[df["Brand"].str.lower() == entities["brand"].lower()]
    if "region" in entities:
        df = df[df["Region"].str.lower() == entities["region"].lower()]
    elif "state" in entities:
        df = df[df["State"].str.lower() == entities["state"].lower()]
    if "strength" in entities and not entities.get("is_lookup"):
        df = df[df["Strength"].str.lower() == entities["strength"].lower()]
    if "milk" in entities and not entities.get("is_lookup"):
        if entities["milk"] == "Black":
            # almost any coffee can be had black - only exclude products that
            # inherently already contain milk powder/creamer (premixes)
            df = df[~df["Milk_Compatibility"].str.contains("Milk Powder|Creamer Included", case=False, regex=True)]
        else:
            df = df[df["Milk_Compatibility"].str.contains(entities["milk"], case=False)]
    if "flavor" in entities and not entities.get("is_lookup"):
        df = df[df["Flavor_Profile"].str.contains(entities["flavor"], case=False)]
    if "type" in entities and not entities.get("is_lookup"):
        df = df[df["Type"].str.lower() == entities["type"].lower()]
    if "brew_format" in entities and not entities.get("is_lookup"):
        df = df[df["Brew_Format"].str.lower() == entities["brew_format"].lower()]
    if "packaging" in entities and not entities.get("is_lookup"):
        df = df[df["Packaging_Type"].str.lower() == entities["packaging"].lower()]
    if "budget" in entities and not entities.get("is_lookup"):
        df = df[df["Price_INR"] <= entities["budget"]]
    if "budget_min" in entities and not entities.get("is_lookup"):
        df = df[df["Price_INR"] >= entities["budget_min"]]
    return df


ACTIONABLE_ENTITY_KEYS = {"product_name", "brand", "region", "state", "strength", "milk", "flavor", "type", "brew_format", "packaging", "budget"}


def has_actionable_filter(entities):
    return any(k in entities for k in ACTIONABLE_ENTITY_KEYS)


def available_flavors():
    all_values = products["Flavor_Profile"].str.split(",")
    return sorted({v.strip() for row in all_values for v in row})


def available_milk_types():
    all_values = products["Milk_Compatibility"].str.split(",")
    unique = sorted({v.strip() for row in all_values for v in row})
    return unique


def available_brew_formats():
    return sorted(products["Brew_Format"].unique())


def get_image_path(row):
    """Use a real photo if one's been added to Image_URL, otherwise fall
    back to the local placeholder icon for that brew format."""
    url = row.get("Image_URL")
    if isinstance(url, str) and url.strip():
        return url.strip()
    icon = BREW_FORMAT_ICON.get(row["Brew_Format"], "default.png")
    return os.path.join(IMAGE_DIR, icon)


def format_price(row):
    if pd.notna(row.get("Price_Per_100g")) and str(row.get("Price_Per_100g")).strip():
        return f"₹{row['Price_INR']} for {row['Pack_Size']} (≈₹{int(float(row['Price_Per_100g']))}/100g)"

    pack = str(row.get("Pack_Size", ""))
    pack_l = pack.lower()
    if "ml" in pack_l:
        return f"₹{row['Price_INR']} for {pack} (sold by volume, not weight)"
    if "pod" in pack_l or "capsule" in pack_l:
        return f"₹{row['Price_INR']} for {pack} (sold as a fixed pack of pods, not by weight)"
    if "sachet" in pack_l or "bag" in pack_l:
        return f"₹{row['Price_INR']} for {pack} (sold as a fixed pack, not by loose weight)"
    return f"₹{row['Price_INR']} for {pack}"


def relaxed_matches(entities):
    """Retry using only the location (region/state), dropping other
    constraints, so we can suggest the closest thing we actually have."""
    if "region" in entities:
        loose = products[products["Region"].str.lower() == entities["region"].lower()]
        if not loose.empty:
            return loose, "region", entities["region"]
    if "state" in entities:
        loose = products[products["State"].str.lower() == entities["state"].lower()]
        if not loose.empty:
            return loose, "state", entities["state"]
    return pd.DataFrame(), None, None


def format_no_match(entities):
    loose, level, label = relaxed_matches(entities)
    if not loose.empty:
        budget_note = ""
        if "budget" in entities:
            cheapest = loose["Price_INR"].min()
            if cheapest > entities["budget"]:
                budget_note = (f" (the cheapest option from {label} is ₹{int(cheapest)}, "
                               f"above your ₹{entities['budget']} budget)")
        lines = [f"I don't have anything matching *all* of that{budget_note}, but here's what I do have from {label}:\n"]
        for _, row in loose.head(3).iterrows():
            lines.append(f"- **{row['Brand']} — {row['Product_Name']}** "
                         f"({row['Brew_Format']}, {row['Strength']}) — {format_price(row)}")
        return "\n".join(lines)

    # nothing matched at all - point to what IS covered rather than a dead end
    if "budget" in entities:
        cheapest_overall = products["Price_INR"].min()
        return (f"I couldn't find anything under ₹{entities['budget']} — my cheapest product overall is "
                f"₹{int(cheapest_overall)}. Try raising your budget, or drop it to see all options.")
    sample_regions = ", ".join(sorted(products["Region"].unique())[:6])
    return (
        "I couldn't find a match for that. My catalog currently covers coffee from "
        f"regions like {sample_regions}, and more. Try naming one of those, or a "
        "preference like strong/mild, or a milk type."
    )


def format_results(df, entities):
    if df.empty:
        return format_no_match(entities)

    lines = []
    state_for_flair = None
    if "region" in entities:
        info = regions[regions["Region"].str.lower() == entities["region"].lower()]
        if not info.empty:
            row = info.iloc[0]
            state_for_flair = row["State"]
            lines.append(f"**{row['Region']}, {row['State']}** typically produces "
                          f"{row['Coffee_Type']} coffee with **{row['Flavor_Notes']}** notes.\n")
    elif "state" in entities:
        state_for_flair = entities["state"]

    if state_for_flair and state_for_flair in STATE_FLAIR:
        lines.insert(0, STATE_FLAIR[state_for_flair] + "\n")

    reason = build_reason(entities)
    if reason and not entities.get("is_lookup"):
        lines.append(reason)

    if entities.get("is_lookup"):
        # explicit "what's available in X" browsing request - a list is the right format here
        lines.append(f"Here are {len(df)} matching option(s):\n")
        for _, row in df.head(5).iterrows():
            lines.append(
                f"- **{row['Brand']} — {row['Product_Name']}** "
                f"({row['Brew_Format']}, {row['Strength']}, {row['Milk_Compatibility']} milk friendly, "
                f"flavor: {row['Flavor_Profile']}) — {format_price(row)}"
            )
    else:
        # default: one confident pick, matching every stated preference - not a list to browse
        pick = df.iloc[0]
        lines.append(
            f"**My pick: {pick['Brand']} — {pick['Product_Name']}**\n"
            f"{pick['Brew_Format']}, {pick['Strength']}, {pick['Milk_Compatibility']} milk friendly, "
            f"flavor: {pick['Flavor_Profile']} — {format_price(pick)}"
        )
        remaining = len(df) - 1
        if remaining > 0:
            lines.append(f"\n_This matches everything you asked for. {remaining} other option(s) "
                         f"also fit just as well if you'd like to see them - just ask._")

    if "requested_grams" in entities:
        requested = entities["requested_grams"]
        pack_grams = []
        for _, row in df.head(5).iterrows():
            m = re.search(r"(\d+)\s*g\b", str(row["Pack_Size"]))
            if m:
                pack_grams.append(int(m.group(1)))
        if pack_grams and requested not in pack_grams:
            sizes = ", ".join(f"{g}g" for g in sorted(set(pack_grams)))
            lines.append(f"\nNote: these aren't sold in {requested}g packs specifically — "
                         f"the pack size(s) available here are {sizes}.")

    return "\n".join(lines)


def build_reason(entities):
    """Short human-readable explanation of what drove the filtering."""
    parts = []
    if "product_name" in entities:
        return f"Matched the specific product: {entities['product_name']}.\n"
    if "brand" in entities:
        parts.append(f"brand: {entities['brand']}")
    if "region" in entities:
        parts.append(f"grown in {entities['region']}")
    elif "state" in entities:
        parts.append(f"from {entities['state']}")
    if "strength" in entities:
        parts.append(f"{entities['strength'].lower()} strength")
    if "milk" in entities:
        if entities["milk"] == "Black":
            parts.append("works well black, no milk needed")
        else:
            parts.append(f"works with {entities['milk'].lower()} milk")
    if "flavor" in entities:
        parts.append(f"{entities['flavor']} flavor notes")
    if "brew_format" in entities:
        parts.append(f"prepared as {entities['brew_format'].lower()}")
    if "packaging" in entities:
        parts.append(f"in {entities['packaging'].lower()}")
    if "budget_min" in entities and "budget" in entities:
        parts.append(f"priced between ₹{entities['budget_min']} and ₹{entities['budget']}")
    elif "budget_min" in entities:
        parts.append(f"above ₹{entities['budget_min']}")
    elif "budget" in entities:
        parts.append(f"within ₹{entities['budget']}")

    if not parts:
        return ""
    return "Matched because you wanted: " + ", ".join(parts) + ".\n"


def log_interaction(user_input, entities, scope, num_matches):
    """Append this turn to a local CSV log - useful evidence for your
    capstone report (most-asked regions, common clarifying questions, etc).
    Note: on free hosting like Streamlit Community Cloud this file resets
    whenever the app restarts/sleeps, so download it periodically if you
    want to keep the history, or point LOG_FILE at a mounted/shared path."""
    is_new = not os.path.exists(LOG_FILE)
    try:
        with open(LOG_FILE, "a", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            if is_new:
                writer.writerow(["timestamp", "user_input", "scope", "entities", "num_matches"])
            writer.writerow([datetime.now().isoformat(timespec="seconds"),
                              user_input, scope, str(entities), num_matches])
    except OSError:
        pass  # don't let logging failures break the chat experience


def log_rating(recommended_product, stars):
    """Append a star rating for a specific recommendation - this is the
    direct 'did this help you' signal for your capstone evaluation, separate
    from the end-of-session Google Form."""
    is_new = not os.path.exists(RATING_LOG_FILE)
    try:
        with open(RATING_LOG_FILE, "a", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            if is_new:
                writer.writerow(["timestamp", "recommended_product", "stars"])
            writer.writerow([datetime.now().isoformat(timespec="seconds"),
                              recommended_product, stars])
    except OSError:
        pass


# ---------- UI ----------
st.set_page_config(page_title="India Coffee Recommender", page_icon="☕")

# Hidden admin dashboard - only visible with the correct secret key in the URL
# e.g. yourapp.streamlit.app/?admin=coffee2026
ADMIN_SECRET = "coffee2026"  # <-- change this to your own secret word
query_params = st.query_params
if query_params.get("admin") == ADMIN_SECRET:
    st.title("☕ Admin Dashboard")
    st.caption("Hidden view - not linked anywhere in the normal chat. Bookmark this URL to check back anytime.")

    st.divider()
    st.subheader("⭐ Ratings")
    if os.path.exists(RATING_LOG_FILE):
        ratings_df = pd.read_csv(RATING_LOG_FILE)
        if not ratings_df.empty:
            col1, col2, col3 = st.columns(3)
            col1.metric("Total ratings", len(ratings_df))
            col2.metric("Average stars", f"{ratings_df['stars'].mean():.1f} ⭐")
            col3.metric("5-star ratings", int((ratings_df["stars"] == 5).sum()))
            st.bar_chart(ratings_df["stars"].value_counts().sort_index())
            st.dataframe(ratings_df.sort_values("timestamp", ascending=False), use_container_width=True, hide_index=True)
            st.download_button("Download ratings as CSV", ratings_df.to_csv(index=False), "ratings_log.csv", "text/csv")
        else:
            st.info("Ratings file exists but is empty.")
    else:
        st.info("No ratings collected yet in this session/deployment.")

    st.divider()
    st.subheader("💬 All Interactions")
    if os.path.exists(LOG_FILE):
        interactions_df = pd.read_csv(LOG_FILE)
        if not interactions_df.empty:
            st.metric("Total messages logged", len(interactions_df))
            st.dataframe(interactions_df.sort_values("timestamp", ascending=False), use_container_width=True, hide_index=True)
            st.download_button("Download interactions as CSV", interactions_df.to_csv(index=False), "interaction_log.csv", "text/csv")
        else:
            st.info("Interaction log exists but is empty.")
    else:
        st.info("No interactions logged yet in this session/deployment.")

    st.divider()
    st.caption("⚠️ Reminder: on free hosting, these files reset whenever the app restarts or sleeps from "
               "inactivity. Download the CSVs above periodically if you want to keep the history.")
    st.stop()  # don't render the normal chat below when in admin mode

st.title("☕ India Coffee Recommender")
st.caption(
    "I help you find Indian coffee brands based on your taste — no more "
    "scrolling through endless options on Amazon or Flipkart. Tell me a "
    "region, a strength, a milk type, or a budget, and I'll match you to "
    "real products."
)

WELCOME_MESSAGE = (
    "Hi! 👋 I'm your coffee recommender, focused only on Indian coffee.\n\n"
    "You can tell me things like:\n"
    "- *\"Strong filter coffee from Chikmagalur\"*\n"
    "- *\"Mild coffee with oat milk\"*\n"
    "- *\"What brands are available in Araku Valley?\"*\n"
    "- *\"Coffee under ₹250\"*\n\n"
    "Not sure what to ask? Tap one of the examples below to get started."
)

FOLLOWUP_MORE_PHRASES = ["show me more", "show the others", "other options", "see them",
                          "show alternatives", "other option", "more options", "yes show",
                          "show more", "show other", "see other", "what else"]


def process_message(text):
    """Single shared pipeline for chat input, quick-start buttons, and the
    sidebar filter, so every path gets logged and answered consistently."""
    # show only the latest exchange, not a growing history - clear everything
    # before adding this new query, so old answers don't stay stacked on screen
    st.session_state["messages"] = []
    st.session_state["messages"].append(("user", text, None))

    # follow-up to "N other options also fit - want to see them?"
    text_l = text.lower().strip()
    last_matches = st.session_state.get("last_matches")
    if (any(p in text_l for p in FOLLOWUP_MORE_PHRASES) or text_l in ("yes", "sure", "ok", "okay"))            and last_matches is not None and len(last_matches) > 1:
        remaining = last_matches.iloc[1:6]
        lines = ["Here are the other options that match just as well:\n"]
        for _, row in remaining.iterrows():
            lines.append(f"- **{row['Brand']} — {row['Product_Name']}** "
                         f"({row['Brew_Format']}, {row['Strength']}) — {format_price(row)}")
        reply = "\n".join(lines)
        log_interaction(text, {}, "coffee", len(remaining))
        st.session_state["messages"].append(("assistant", reply, remaining))
        st.session_state["last_matches"] = None  # shown already, don't offer again
        return

    entities = extract_entities(text)
    scope = message_scope(text, entities)
    products_for_images = None

    if entities.get("foreign_brand"):
        named = entities["foreign_brand"].title()
        alt_entities = {k: v for k, v in entities.items()
                         if k in ("region", "state", "strength", "milk", "flavor", "type", "brew_format")}
        alt_matches = filter_products(alt_entities) if alt_entities else pd.DataFrame()
        if alt_matches.empty:
            alt_matches = products.sample(min(3, len(products)), random_state=42)
        alt_lines = [f"- **{row['Brand']} — {row['Product_Name']}** ({row['Brew_Format']}, {row['Strength']}) — {format_price(row)}"
                     for _, row in alt_matches.head(3).iterrows()]
        reply = (f"I'm a bot built only for Indian-grown coffee, so I don't have data on {named} — "
                 f"that's not an Indian-sourced brand. Here's the closest match from Indian coffee I do have:\n\n"
                 + "\n".join(alt_lines))
        num_matches = len(alt_matches)
        if not alt_matches.empty:
            products_for_images = alt_matches.head(3)
        log_interaction(text, entities, "coffee", num_matches)
        st.session_state["messages"].append(("assistant", reply, products_for_images))
        return

    if scope == "off_topic":
        reply = OFF_TOPIC_MESSAGE
        num_matches = 0
    elif scope == "greeting":
        reply = random.choice(GREETING_REPLIES)
        num_matches = 0
    elif entities.get("milk_lookup"):
        options = ", ".join(available_milk_types())
        reply = f"Here's what I can filter by for milk: **{options}**. Just tell me which one you'd like."
        num_matches = 0
    elif entities.get("brew_format_lookup"):
        options = ", ".join(available_brew_formats())
        reply = (f"I can search by these brew formats: **{options}**. "
                 "For example: Traditional Filter (metal filter/decoction), "
                 "Drip Bag (dip it in your cup), Instant Sachet (just add hot water), "
                 "or Cold Brew Concentrate. Which one suits you?")
        num_matches = 0
    elif entities.get("packaging_lookup"):
        options = ", ".join(sorted(products["Packaging_Type"].unique()))
        reply = (f"I can filter by packaging too: **{options}**. "
                 "Do you want it in a glass jar, a pouch/packet, or something else?")
        num_matches = 0
    elif entities.get("unknown_flavor"):
        options = ", ".join(available_flavors())
        reply = (f"I don't have that specific flavor in my list. What I do have: "
                 f"**{options}**. Want me to match one of these to a region or brand?")
        num_matches = 0
    elif not has_actionable_filter(entities):
        # scope is "coffee" only because of a generic word like "coffee" itself -
        # too vague to filter on, so ask rather than dumping the whole catalog
        reply = ("I'd love to help — could you tell me a bit more? A region "
                 "(like Chikmagalur or Araku Valley), how strong you like it, "
                 "a milk type, or a budget all work.")
        num_matches = 0
    else:
        matches = filter_products(entities)
        reply = format_results(matches, entities)
        num_matches = len(matches)
        if not matches.empty and not entities.get("is_lookup"):
            products_for_images = matches.head(5)
        st.session_state["last_matches"] = matches if (not matches.empty and not entities.get("is_lookup") and len(matches) > 1) else None

    log_interaction(text, entities, scope, num_matches)
    st.session_state["messages"].append(("assistant", reply, products_for_images))
    st.session_state["scroll_to_latest"] = True


if "messages" not in st.session_state:
    st.session_state["messages"] = [("assistant", WELCOME_MESSAGE, None)]
if "conversation_rated" not in st.session_state:
    st.session_state["conversation_rated"] = False
if "last_recommended_product" not in st.session_state:
    st.session_state["last_recommended_product"] = None

with st.expander("🔍 Or filter manually", expanded=True):
    with st.form(key="filter_form"):
        sel_region = st.selectbox("Region", ["Any"] + REGIONS_WITH_PRODUCTS, key="filter_region")
        sel_strength = st.selectbox("Strength", ["Any", "Strong", "Medium", "Mild"], key="filter_strength")
        sel_milk = st.selectbox("Milk", ["Any", "Black (No Milk)"] + available_milk_types(), key="filter_milk")
        sel_brew_format = st.selectbox("Brew Format", ["Any"] + available_brew_formats(), key="filter_brew_format")
        sel_price_band = st.selectbox(
            "Price Range",
            ["Any", "Under ₹50", "₹50 – ₹100", "₹100 – ₹200", "₹200 – ₹300", "₹300 – ₹500", "Above ₹500"],
            key="filter_price_band",
            help="Based on real prices in the catalog (₹2 – ₹940)"
        )
        filter_submitted = st.form_submit_button("Get recommendations")
    if filter_submitted:
        parts = []
        if sel_region != "Any":
            parts.append(sel_region)
        if sel_strength != "Any":
            parts.append(sel_strength.lower())
        if sel_milk == "Black (No Milk)":
            parts.append("black, no milk")
        elif sel_milk != "Any":
            parts.append(f"{sel_milk.lower()} milk")
        if sel_brew_format != "Any":
            parts.append(sel_brew_format)
        price_band_text = {
            "Under ₹50": "under 50",
            "₹50 – ₹100": "between 50 to 100",
            "₹100 – ₹200": "between 100 to 200",
            "₹200 – ₹300": "between 200 to 300",
            "₹300 – ₹500": "between 300 to 500",
            "Above ₹500": "above 500",
        }.get(sel_price_band)
        if price_band_text:
            parts.append(price_band_text)
        summary_text = "Manual filter: " + ", ".join(parts) if parts else "Manual filter: any coffee"
        process_message(summary_text)
        st.rerun()

total_messages = len(st.session_state["messages"])
for idx, (role, content, product_rows) in enumerate(st.session_state["messages"]):
    if idx == total_messages - 1:
        st.markdown('<div id="latest-response-anchor"></div>', unsafe_allow_html=True)
    with st.chat_message(role):
        st.markdown(content)
        if product_rows is not None and not product_rows.empty:
            cols = st.columns(min(len(product_rows), 5))
            for col, (_, prow) in zip(cols, product_rows.iterrows()):
                with col:
                    st.image(get_image_path(prow), use_container_width=True)
                    st.caption(f"{prow['Brand']}\n{format_price(prow)}")

        if role == "assistant" and "**My pick:" in content:
            st.session_state["last_recommended_product"] = content.split("**My pick:")[1].split("**")[0].strip()
        if role == "assistant" and idx > 0:
            # any real response beyond the welcome message counts as "had a chat worth rating",
            # even if it was a fallback/no-exact-match reply rather than a confident single pick
            st.session_state["has_had_response"] = True

if st.session_state.get("scroll_to_latest"):
    st.session_state["scroll_to_latest"] = False
    st.markdown("""
        <script>
        (function() {
            function getDoc() {
                try { if (window.parent && window.parent.document) return window.parent.document; } catch (e) {}
                return document;
            }
            function tryScroll(attemptsLeft) {
                const doc = getDoc();
                const anchor = doc.getElementById("latest-response-anchor");
                if (anchor) {
                    anchor.scrollIntoView({behavior: "smooth", block: "start"});
                    return;
                }
                if (attemptsLeft > 0) {
                    setTimeout(function() { tryScroll(attemptsLeft - 1); }, 200);
                } else {
                    // fallback: couldn't find the specific anchor, just scroll the whole page down
                    try {
                        const win = window.parent || window;
                        win.scrollTo({top: win.document.body.scrollHeight, behavior: "smooth"});
                    } catch (e) {}
                }
            }
            tryScroll(10);
        })();
        </script>
    """, unsafe_allow_html=True)

# quick-start buttons only shown before the user has typed anything, so
# they don't clutter an already-active conversation
if len(st.session_state["messages"]) == 1:
    st.write("Try one of these:")
    cols = st.columns(len(QUICK_START_PROMPTS))
    for col, prompt in zip(cols, QUICK_START_PROMPTS):
        if col.button(prompt, use_container_width=True):
            process_message(prompt)
            st.rerun()

with st.form(key="user_message_form", clear_on_submit=True):
    user_input = st.text_input("Ask me anything about Indian coffee:",
                                placeholder="e.g. I had strong coffee in Chikmagalur, want something similar")
    submitted = st.form_submit_button("Send")
if submitted and user_input:
    process_message(user_input)
    st.rerun()

st.divider()

if st.session_state["last_recommended_product"]:
    st.info("👆 **Your recommendation is above this line** — scroll up to see it if you landed here first.")

if st.session_state.get("has_had_response") and not st.session_state["conversation_rated"]:
    if st.session_state["last_recommended_product"]:
        st.markdown(f"**{random.choice(CLOSING_MESSAGES)}** I hope *{st.session_state['last_recommended_product']}* "
                   f"turns out to be exactly what you were looking for.")
    else:
        st.markdown(f"**{random.choice(CLOSING_MESSAGES)}** I hope one of the suggestions above works for you!")
    st.caption("Before you go — how helpful was this chat overall?")
    star_cols = st.columns(5)
    for star_n, scol in enumerate(star_cols, start=1):
        if scol.button("⭐" * star_n, key=f"session_rate_{star_n}"):
            log_rating(st.session_state["last_recommended_product"] or "No exact match - fallback suggestion", star_n)
            st.session_state["conversation_rated"] = True
            st.rerun()
elif st.session_state["conversation_rated"]:
    st.caption("Thanks for rating this chat! 🙏")

st.markdown(f"Enjoyed the recommendations? [Share quick feedback here]({GOOGLE_FORM_URL}) — it takes 1 minute.")
